print('What is your name?')
name = input('     Input your name: ')
print('How old are you?')
age = input('     Input your age: ')
print('Where are you live?')
address = input('     Input your address: ')
print('Hello, %s!' %(name))
print('Your age is %s' %(age))
print('You live in %s' %(address))